require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/blog/authors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Blog::Author. As you add validations to Blog::Author, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Blog::Author.create! valid_attributes
      get blog_authors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      author = Blog::Author.create! valid_attributes
      get blog_author_url(author)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_blog_author_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      author = Blog::Author.create! valid_attributes
      get edit_blog_author_url(author)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Blog::Author" do
        expect {
          post blog_authors_url, params: { blog_author: valid_attributes }
        }.to change(Blog::Author, :count).by(1)
      end

      it "redirects to the created blog_author" do
        post blog_authors_url, params: { blog_author: valid_attributes }
        expect(response).to redirect_to(blog_author_url(Blog::Author.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Blog::Author" do
        expect {
          post blog_authors_url, params: { blog_author: invalid_attributes }
        }.to change(Blog::Author, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post blog_authors_url, params: { blog_author: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested blog_author" do
        author = Blog::Author.create! valid_attributes
        patch blog_author_url(author), params: { blog_author: new_attributes }
        author.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the blog_author" do
        author = Blog::Author.create! valid_attributes
        patch blog_author_url(author), params: { blog_author: new_attributes }
        author.reload
        expect(response).to redirect_to(blog_author_url(author))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        author = Blog::Author.create! valid_attributes
        patch blog_author_url(author), params: { blog_author: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested blog_author" do
      author = Blog::Author.create! valid_attributes
      expect {
        delete blog_author_url(author)
      }.to change(Blog::Author, :count).by(-1)
    end

    it "redirects to the blog_authors list" do
      author = Blog::Author.create! valid_attributes
      delete blog_author_url(author)
      expect(response).to redirect_to(blog_authors_url)
    end
  end
end
