# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/blog/comments' do
  # This should return the minimal set of attributes required to create a valid
  # Blog::Comment. As you add validations to Blog::Comment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Blog::Comment' do
        expect do
          post blog_comments_url, params: { blog_comment: valid_attributes }
        end.to change(Blog::Comment, :count).by(1)
      end

      it 'redirects to the created blog_comment' do
        post blog_comments_url, params: { blog_comment: valid_attributes }
        expect(response).to redirect_to(blog_comment_url(Blog::Comment.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Blog::Comment' do
        expect do
          post blog_comments_url, params: { blog_comment: invalid_attributes }
        end.not_to change(Blog::Comment, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post blog_comments_url, params: { blog_comment: invalid_attributes }
        expect(response.has_http_status?(:unprocessable_entity)).to be(true)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested blog_comment' do
        comment = Blog::Comment.create! valid_attributes
        patch blog_comment_url(comment), params: { blog_comment: new_attributes }
        comment.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the blog_comment' do
        comment = Blog::Comment.create! valid_attributes
        patch blog_comment_url(comment), params: { blog_comment: new_attributes }
        comment.reload
        expect(response).to redirect_to(blog_comment_url(comment))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        comment = Blog::Comment.create! valid_attributes
        patch blog_comment_url(comment), params: { blog_comment: invalid_attributes }
        expect(response.has_http_status?(:unprocessable_entity)).to be(true)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested blog_comment' do
      comment = Blog::Comment.create! valid_attributes
      expect do
        delete blog_comment_url(comment)
      end.to change(Blog::Comment, :count).by(-1)
    end

    it 'redirects to the blog_comments list' do
      comment = Blog::Comment.create! valid_attributes
      delete blog_comment_url(comment)
      expect(response).to redirect_to(blog_comments_url)
    end
  end
end
